// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent.proto

package com.immomo.datainfo.protocol;

public final class AgentProtocolProtos {
  private AgentProtocolProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeartBeatRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string status = 1;
    /**
     * <code>required string status = 1;</code>
     *
     * <pre>
     * status name
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>required string status = 1;</code>
     *
     * <pre>
     * status name
     * </pre>
     */
    String getStatus();
    /**
     * <code>required string status = 1;</code>
     *
     * <pre>
     * status name
     * </pre>
     */
    com.google.protobuf.ByteString
        getStatusBytes();
  }
  /**
   * Protobuf type {@code avalon.core.HeartBeatRequestProto}
   */
  public static final class HeartBeatRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements HeartBeatRequestProtoOrBuilder {
    // Use HeartBeatRequestProto.newBuilder() to construct.
    private HeartBeatRequestProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartBeatRequestProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartBeatRequestProto defaultInstance;
    public static HeartBeatRequestProto getDefaultInstance() {
      return defaultInstance;
    }

    public HeartBeatRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatRequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              status_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AgentProtocolProtos.internal_static_avalon_core_HeartBeatRequestProto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AgentProtocolProtos.internal_static_avalon_core_HeartBeatRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeartBeatRequestProto.class, Builder.class);
    }

    public static com.google.protobuf.Parser<HeartBeatRequestProto> PARSER =
        new com.google.protobuf.AbstractParser<HeartBeatRequestProto>() {
      public HeartBeatRequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatRequestProto(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<HeartBeatRequestProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private Object status_;
    /**
     * <code>required string status = 1;</code>
     *
     * <pre>
     * status name
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string status = 1;</code>
     *
     * <pre>
     * status name
     * </pre>
     */
    public String getStatus() {
      Object ref = status_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string status = 1;</code>
     *
     * <pre>
     * status name
     * </pre>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      status_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStatusBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStatusBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HeartBeatRequestProto)) {
        return super.equals(obj);
      }
      HeartBeatRequestProto other = (HeartBeatRequestProto) obj;

      boolean result = true;
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && getStatus()
            .equals(other.getStatus());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HeartBeatRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HeartBeatRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static HeartBeatRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static HeartBeatRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static HeartBeatRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HeartBeatRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HeartBeatRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code avalon.core.HeartBeatRequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements HeartBeatRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AgentProtocolProtos.internal_static_avalon_core_HeartBeatRequestProto_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AgentProtocolProtos.internal_static_avalon_core_HeartBeatRequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeartBeatRequestProto.class, Builder.class);
      }

      // Construct using com.immomo.datainfo.protocol.AgentProtocolProtos.HeartBeatRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AgentProtocolProtos.internal_static_avalon_core_HeartBeatRequestProto_descriptor;
      }

      public HeartBeatRequestProto getDefaultInstanceForType() {
        return HeartBeatRequestProto.getDefaultInstance();
      }

      public HeartBeatRequestProto build() {
        HeartBeatRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HeartBeatRequestProto buildPartial() {
        HeartBeatRequestProto result = new HeartBeatRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HeartBeatRequestProto) {
          return mergeFrom((HeartBeatRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HeartBeatRequestProto other) {
        if (other == HeartBeatRequestProto.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          bitField0_ |= 0x00000001;
          status_ = other.status_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HeartBeatRequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HeartBeatRequestProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string status = 1;
      private Object status_ = "";
      /**
       * <code>required string status = 1;</code>
       *
       * <pre>
       * status name
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string status = 1;</code>
       *
       * <pre>
       * status name
       * </pre>
       */
      public String getStatus() {
        Object ref = status_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string status = 1;</code>
       *
       * <pre>
       * status name
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string status = 1;</code>
       *
       * <pre>
       * status name
       * </pre>
       */
      public Builder setStatus(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string status = 1;</code>
       *
       * <pre>
       * status name
       * </pre>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>required string status = 1;</code>
       *
       * <pre>
       * status name
       * </pre>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:avalon.core.HeartBeatRequestProto)
    }

    static {
      defaultInstance = new HeartBeatRequestProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:avalon.core.HeartBeatRequestProto)
  }

  public interface HeartBeatResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .avalon.core.JobInfoProto jobInfos = 1;
    /**
     * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
     */
    java.util.List<com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto> 
        getJobInfosList();
    /**
     * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
     */
    com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto getJobInfos(int index);
    /**
     * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
     */
    int getJobInfosCount();
    /**
     * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
     */
    java.util.List<? extends com.immomo.datainfo.protocol.AvalonProtos.JobInfoProtoOrBuilder> 
        getJobInfosOrBuilderList();
    /**
     * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
     */
    com.immomo.datainfo.protocol.AvalonProtos.JobInfoProtoOrBuilder getJobInfosOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code avalon.core.HeartBeatResponseProto}
   */
  public static final class HeartBeatResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements HeartBeatResponseProtoOrBuilder {
    // Use HeartBeatResponseProto.newBuilder() to construct.
    private HeartBeatResponseProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartBeatResponseProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartBeatResponseProto defaultInstance;
    public static HeartBeatResponseProto getDefaultInstance() {
      return defaultInstance;
    }

    public HeartBeatResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatResponseProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                jobInfos_ = new java.util.ArrayList<com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              jobInfos_.add(input.readMessage(com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          jobInfos_ = java.util.Collections.unmodifiableList(jobInfos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AgentProtocolProtos.internal_static_avalon_core_HeartBeatResponseProto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AgentProtocolProtos.internal_static_avalon_core_HeartBeatResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeartBeatResponseProto.class, Builder.class);
    }

    public static com.google.protobuf.Parser<HeartBeatResponseProto> PARSER =
        new com.google.protobuf.AbstractParser<HeartBeatResponseProto>() {
      public HeartBeatResponseProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatResponseProto(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<HeartBeatResponseProto> getParserForType() {
      return PARSER;
    }

    // repeated .avalon.core.JobInfoProto jobInfos = 1;
    public static final int JOBINFOS_FIELD_NUMBER = 1;
    private java.util.List<com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto> jobInfos_;
    /**
     * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
     */
    public java.util.List<com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto> getJobInfosList() {
      return jobInfos_;
    }
    /**
     * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
     */
    public java.util.List<? extends com.immomo.datainfo.protocol.AvalonProtos.JobInfoProtoOrBuilder> 
        getJobInfosOrBuilderList() {
      return jobInfos_;
    }
    /**
     * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
     */
    public int getJobInfosCount() {
      return jobInfos_.size();
    }
    /**
     * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
     */
    public com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto getJobInfos(int index) {
      return jobInfos_.get(index);
    }
    /**
     * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
     */
    public com.immomo.datainfo.protocol.AvalonProtos.JobInfoProtoOrBuilder getJobInfosOrBuilder(
        int index) {
      return jobInfos_.get(index);
    }

    private void initFields() {
      jobInfos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getJobInfosCount(); i++) {
        if (!getJobInfos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < jobInfos_.size(); i++) {
        output.writeMessage(1, jobInfos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < jobInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, jobInfos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HeartBeatResponseProto)) {
        return super.equals(obj);
      }
      HeartBeatResponseProto other = (HeartBeatResponseProto) obj;

      boolean result = true;
      result = result && getJobInfosList()
          .equals(other.getJobInfosList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getJobInfosCount() > 0) {
        hash = (37 * hash) + JOBINFOS_FIELD_NUMBER;
        hash = (53 * hash) + getJobInfosList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HeartBeatResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HeartBeatResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static HeartBeatResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static HeartBeatResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static HeartBeatResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HeartBeatResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HeartBeatResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code avalon.core.HeartBeatResponseProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements HeartBeatResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AgentProtocolProtos.internal_static_avalon_core_HeartBeatResponseProto_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AgentProtocolProtos.internal_static_avalon_core_HeartBeatResponseProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeartBeatResponseProto.class, Builder.class);
      }

      // Construct using com.immomo.datainfo.protocol.AgentProtocolProtos.HeartBeatResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getJobInfosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (jobInfosBuilder_ == null) {
          jobInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          jobInfosBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AgentProtocolProtos.internal_static_avalon_core_HeartBeatResponseProto_descriptor;
      }

      public HeartBeatResponseProto getDefaultInstanceForType() {
        return HeartBeatResponseProto.getDefaultInstance();
      }

      public HeartBeatResponseProto build() {
        HeartBeatResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HeartBeatResponseProto buildPartial() {
        HeartBeatResponseProto result = new HeartBeatResponseProto(this);
        int from_bitField0_ = bitField0_;
        if (jobInfosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            jobInfos_ = java.util.Collections.unmodifiableList(jobInfos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.jobInfos_ = jobInfos_;
        } else {
          result.jobInfos_ = jobInfosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HeartBeatResponseProto) {
          return mergeFrom((HeartBeatResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HeartBeatResponseProto other) {
        if (other == HeartBeatResponseProto.getDefaultInstance()) return this;
        if (jobInfosBuilder_ == null) {
          if (!other.jobInfos_.isEmpty()) {
            if (jobInfos_.isEmpty()) {
              jobInfos_ = other.jobInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureJobInfosIsMutable();
              jobInfos_.addAll(other.jobInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.jobInfos_.isEmpty()) {
            if (jobInfosBuilder_.isEmpty()) {
              jobInfosBuilder_.dispose();
              jobInfosBuilder_ = null;
              jobInfos_ = other.jobInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              jobInfosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getJobInfosFieldBuilder() : null;
            } else {
              jobInfosBuilder_.addAllMessages(other.jobInfos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getJobInfosCount(); i++) {
          if (!getJobInfos(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HeartBeatResponseProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HeartBeatResponseProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .avalon.core.JobInfoProto jobInfos = 1;
      private java.util.List<com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto> jobInfos_ =
        java.util.Collections.emptyList();
      private void ensureJobInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          jobInfos_ = new java.util.ArrayList<com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto>(jobInfos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto, com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto.Builder, com.immomo.datainfo.protocol.AvalonProtos.JobInfoProtoOrBuilder> jobInfosBuilder_;

      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public java.util.List<com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto> getJobInfosList() {
        if (jobInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(jobInfos_);
        } else {
          return jobInfosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public int getJobInfosCount() {
        if (jobInfosBuilder_ == null) {
          return jobInfos_.size();
        } else {
          return jobInfosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto getJobInfos(int index) {
        if (jobInfosBuilder_ == null) {
          return jobInfos_.get(index);
        } else {
          return jobInfosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public Builder setJobInfos(
          int index, com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto value) {
        if (jobInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobInfosIsMutable();
          jobInfos_.set(index, value);
          onChanged();
        } else {
          jobInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public Builder setJobInfos(
          int index, com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto.Builder builderForValue) {
        if (jobInfosBuilder_ == null) {
          ensureJobInfosIsMutable();
          jobInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          jobInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public Builder addJobInfos(com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto value) {
        if (jobInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobInfosIsMutable();
          jobInfos_.add(value);
          onChanged();
        } else {
          jobInfosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public Builder addJobInfos(
          int index, com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto value) {
        if (jobInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobInfosIsMutable();
          jobInfos_.add(index, value);
          onChanged();
        } else {
          jobInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public Builder addJobInfos(
          com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto.Builder builderForValue) {
        if (jobInfosBuilder_ == null) {
          ensureJobInfosIsMutable();
          jobInfos_.add(builderForValue.build());
          onChanged();
        } else {
          jobInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public Builder addJobInfos(
          int index, com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto.Builder builderForValue) {
        if (jobInfosBuilder_ == null) {
          ensureJobInfosIsMutable();
          jobInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          jobInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public Builder addAllJobInfos(
          Iterable<? extends com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto> values) {
        if (jobInfosBuilder_ == null) {
          ensureJobInfosIsMutable();
          super.addAll(values, jobInfos_);
          onChanged();
        } else {
          jobInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public Builder clearJobInfos() {
        if (jobInfosBuilder_ == null) {
          jobInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          jobInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public Builder removeJobInfos(int index) {
        if (jobInfosBuilder_ == null) {
          ensureJobInfosIsMutable();
          jobInfos_.remove(index);
          onChanged();
        } else {
          jobInfosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto.Builder getJobInfosBuilder(
          int index) {
        return getJobInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public com.immomo.datainfo.protocol.AvalonProtos.JobInfoProtoOrBuilder getJobInfosOrBuilder(
          int index) {
        if (jobInfosBuilder_ == null) {
          return jobInfos_.get(index);  } else {
          return jobInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public java.util.List<? extends com.immomo.datainfo.protocol.AvalonProtos.JobInfoProtoOrBuilder> 
           getJobInfosOrBuilderList() {
        if (jobInfosBuilder_ != null) {
          return jobInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(jobInfos_);
        }
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto.Builder addJobInfosBuilder() {
        return getJobInfosFieldBuilder().addBuilder(
            com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto.getDefaultInstance());
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto.Builder addJobInfosBuilder(
          int index) {
        return getJobInfosFieldBuilder().addBuilder(
            index, com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto.getDefaultInstance());
      }
      /**
       * <code>repeated .avalon.core.JobInfoProto jobInfos = 1;</code>
       */
      public java.util.List<com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto.Builder> 
           getJobInfosBuilderList() {
        return getJobInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto, com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto.Builder, com.immomo.datainfo.protocol.AvalonProtos.JobInfoProtoOrBuilder> 
          getJobInfosFieldBuilder() {
        if (jobInfosBuilder_ == null) {
          jobInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto, com.immomo.datainfo.protocol.AvalonProtos.JobInfoProto.Builder, com.immomo.datainfo.protocol.AvalonProtos.JobInfoProtoOrBuilder>(
                  jobInfos_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          jobInfos_ = null;
        }
        return jobInfosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:avalon.core.HeartBeatResponseProto)
    }

    static {
      defaultInstance = new HeartBeatResponseProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:avalon.core.HeartBeatResponseProto)
  }

  /**
   * Protobuf service {@code avalon.core.AgentAvalonProtocol}
   */
  public static abstract class AgentAvalonProtocol
      implements com.google.protobuf.Service {
    protected AgentAvalonProtocol() {}

    public interface Interface {
      /**
       * <code>rpc sendHeartBeat(.avalon.core.HeartBeatRequestProto) returns (.avalon.core.HeartBeatResponseProto);</code>
       */
      public abstract void sendHeartBeat(
              com.google.protobuf.RpcController controller,
              HeartBeatRequestProto request,
              com.google.protobuf.RpcCallback<HeartBeatResponseProto> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new AgentAvalonProtocol() {
        @Override
        public  void sendHeartBeat(
            com.google.protobuf.RpcController controller,
            HeartBeatRequestProto request,
            com.google.protobuf.RpcCallback<HeartBeatResponseProto> done) {
          impl.sendHeartBeat(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.sendHeartBeat(controller, (HeartBeatRequestProto)request);
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return HeartBeatRequestProto.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return HeartBeatResponseProto.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc sendHeartBeat(.avalon.core.HeartBeatRequestProto) returns (.avalon.core.HeartBeatResponseProto);</code>
     */
    public abstract void sendHeartBeat(
        com.google.protobuf.RpcController controller,
        HeartBeatRequestProto request,
        com.google.protobuf.RpcCallback<HeartBeatResponseProto> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return AgentProtocolProtos.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.sendHeartBeat(controller, (HeartBeatRequestProto)request,
            com.google.protobuf.RpcUtil.<HeartBeatResponseProto>specializeCallback(
              done));
          return;
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return HeartBeatRequestProto.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return HeartBeatResponseProto.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends AgentAvalonProtocol implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void sendHeartBeat(
          com.google.protobuf.RpcController controller,
          HeartBeatRequestProto request,
          com.google.protobuf.RpcCallback<HeartBeatResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          HeartBeatResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            HeartBeatResponseProto.class,
            HeartBeatResponseProto.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public HeartBeatResponseProto sendHeartBeat(
              com.google.protobuf.RpcController controller,
              HeartBeatRequestProto request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public HeartBeatResponseProto sendHeartBeat(
          com.google.protobuf.RpcController controller,
          HeartBeatRequestProto request)
          throws com.google.protobuf.ServiceException {
        return (HeartBeatResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          HeartBeatResponseProto.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:avalon.core.AgentAvalonProtocol)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_avalon_core_HeartBeatRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_avalon_core_HeartBeatRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_avalon_core_HeartBeatResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_avalon_core_HeartBeatResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013agent.proto\022\013avalon.core\032\014avalon.proto" +
      "\"\'\n\025HeartBeatRequestProto\022\016\n\006status\030\001 \002(" +
      "\t\"E\n\026HeartBeatResponseProto\022+\n\010jobInfos\030" +
      "\001 \003(\0132\031.avalon.core.JobInfoProto2o\n\023Agen" +
      "tAvalonProtocol\022X\n\rsendHeartBeat\022\".avalo" +
      "n.core.HeartBeatRequestProto\032#.avalon.co" +
      "re.HeartBeatResponseProtoB9\n\034com.immomo." +
      "datainfo.protocolB\023AgentProtocolProtos\210\001" +
      "\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_avalon_core_HeartBeatRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_avalon_core_HeartBeatRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_avalon_core_HeartBeatRequestProto_descriptor,
              new String[] { "Status", });
          internal_static_avalon_core_HeartBeatResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_avalon_core_HeartBeatResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_avalon_core_HeartBeatResponseProto_descriptor,
              new String[] { "JobInfos", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.immomo.datainfo.protocol.AvalonProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
